import { hashSync } from "bcrypt-ts-edge";

const sampleData = {
  users: [
    {
      name: "أحمد محمد",
      email: "ahmed@example.com",
      password: hashSync("123456", 10),
      role: "admin",
    },

    {
      name: "سارة علي",
      email: "sara@example.com",
      password: hashSync("123456", 10),
      role: "user",
    },
  ],

  products: [
    {
      name: "قميص بولو الرياضي المرن",
      slug: "polo-sporting-stretch-shirt",
      category: "قمصان رجالي كلاسيكية",
      description: "ستايل بولو الكلاسيكي مع راحة عصرية",
      images: [
        "/images/sample-products/p1-1.jpg",
        "/images/sample-products/p1-2.jpg",
      ],
      price: 59.99,
      brand: "بولو",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      name: "قميص بروكس براذرز بأكمام طويلة",
      slug: "brooks-brothers-long-sleeved-shirt",
      category: "قمصان رجالي كلاسيكية",
      description: "أناقة خالدة وراحة فاخرة",
      images: [
        "/images/sample-products/p2-1.jpg",
        "/images/sample-products/p2-2.jpg",
      ],
      price: 85.9,
      brand: "بروكس براذرز",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "banner-2.jpg",
    },
    {
      name: "قميص تومي هيلفيغر الكلاسيكي",
      slug: "tommy-hilfiger-classic-fit-dress-shirt",
      category: "قمصان رجالي كلاسيكية",
      description: "مزيج مثالي من الأناقة والراحة",
      images: [
        "/images/sample-products/p3-1.jpg",
        "/images/sample-products/p3-2.jpg",
      ],
      price: 99.95,
      brand: "تومي هيلفيغر",
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "قميص كالفن كلاين بقصة ضيقة ومرنة",
      slug: "calvin-klein-slim-fit-stretch-shirt",
      category: "قمصان رجالي كلاسيكية",
      description: "تصميم أنيق مع قماش مرن مريح",
      images: [
        "/images/sample-products/p4-1.jpg",
        "/images/sample-products/p4-2.jpg",
      ],
      price: 39.95,
      brand: "كالفن كلاين",
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "قميص بولو رالف لورين أوكسفورد",
      slug: "polo-ralph-lauren-oxford-shirt",
      category: "قمصان رجالي كلاسيكية",
      description: "تصميم بولو الأيقوني بقماش أوكسفورد الفاخر",
      images: [
        "/images/sample-products/p5-1.jpg",
        "/images/sample-products/p5-2.jpg",
      ],
      price: 79.99,
      brand: "بولو",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "هودي بولو الكلاسيكي الوردي",
      slug: "polo-classic-pink-hoodie",
      category: "سويتشيرتات رجالي",
      description: "ناعم وأنيق ومثالي لأيام الراحة",
      images: [
        "/images/sample-products/p6-1.jpg",
        "/images/sample-products/p6-2.jpg",
      ],
      price: 99.99,
      brand: "بولو",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
